### ISSUE TITLE
notes about Bios 1.25

### ISSUE THREAD

**Issue by katakombi** [fiji-flo/x1carbon2018s3#15]
Dear fiji-flo,

 thanks for this patch! I tried it on the latest BIOS version 1.25 and the DSDT patching yielded in errors.
I manually corrected them and got it to compile and work, however, I barely knew what I was doing and hence still testing thoroughly.

I did not set any ACPI vendor string, my grub commandline:
"quiet splash psmouse.synaptics_intertouch=1 iwlwifi.power_save=1 iwlwifi.d0i3_disable=0 iwlwifi=uapsd_disable=0 thinkpad_acpi.fan_control=1 mem_sleep_default=deep"

Please find my files here:
https://github.com/katakombi/lm19-x1c6/blob/master/dsdt-1.25.orig.dsl
https://github.com/katakombi/lm19-x1c6/blob/master/dsdt-1.25.patched.dsl

I give you this info in the hope that you can add some information about this latest version of the BIOS!
thanks and greets

**Comment by katakombi** [comment]
oookay... Ive checked it and seemingly USB + track pad+touch stick stop working after resume.
USB is okay after reboot, trackpad and track point require a cold restart to come up again.

**Comment by fiji-flo** [comment]
That sounds like the patch isn't applied and you're using S0i3 sleep. These are known issues there.

The errors are probably due to an older version of `iasl`. I'll get back to you after work.

**Comment by katakombi** [comment]
```
iasl -v

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180105
Copyright (c) 2000 - 2018 Intel Corporation

dmesg | grep 'ACPI: (supports'
[    0.194101] ACPI: (supports S0 S3 S4 S5)
```

**Comment by katakombi** [comment]
btw I am using Linux Mint 19 not Arch Linux. Maybe something still wrong with `/etc/default/grub`

**Comment by katakombi** [comment]
thanks ... going to try that :)

**Comment by fiji-flo** [comment]
Can you post the output of:
```
cat /sys/power/mem_sleep
```
and 
```
journalctl -g "PM:"
```

**Comment by katakombi** [comment]
Okay using the most recent version of `iasl` made it work for me:
```
./iasl -v

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180629
Copyright (c) 2000 - 2018 Intel Corporation
```
