### ISSUE TITLE
Q: Is BIOS 1.25 a prerequisite?

### ISSUE THREAD

**Issue by HenrikBengtsson** [fiji-flo/x1carbon2018s3#17]
I noticed that "The current BIOS version for the X1C6 is 1.25." is mentioned under Prerequisites -> BIOS.

Is that a required prerequisite, a recommendation, or just a comment that the most recent version available is 1.25?

I wonder because when I'll try to apply this fix later today and I find my BIOS to be older (brand new X1C6), should I bother upgrading first or not?

**Comment by fiji-flo** [comment]
You're right. It's optional. I added a optional hint in #18 

This was a remainder from a early version, when there was a hard coded patch file.

Thanks for bringing this up.

I'd still recommend doing the update. There were quite a few security fixes in the recent updates.

**Comment by HenrikBengtsson** [comment]
Thxs
