### ISSUE TITLE
/acpi_override not found.

### ISSUE THREAD

**Issue by BkunS** [fiji-flo/x1carbon2018s3#23]
Ubuntu 18.04, added /acpi_override in grub after initrd, but it says '/acpi_override not found' on boot. Tried to find the acpi_override file, but it's not there under root dir.

**Comment by mattip** [comment]
Do you have a single partition and `/boot` is a directory not a mount (hint - what is the incantation for `initramfs-linux.img`)? If so you should use `/boot/acpi_override`, as documented in the [readme](https://github.com/fiji-flo/x1carbon2018s3#some-notes)

**Comment by BkunS** [comment]
I use single partition. I also checked /boot dir, but acpi_override is not there either. Also, I'm getting 64 errors running the script, not sure if it's normal or not: Compilation complete. 64 Errors, 332 Warnings, 116 Remarks, 6298 Optimizations, 46 Constants Folded.

**Comment by dal00** [comment]
I guess you updated your bios with the automatic bios update found in fwupd?
You will need to get a newer iasl to be able to build the patch.

**Comment by BkunS** [comment]
Both iasl (20180105-1) and cpio (2.12+dfsg-6) are latest. I installed the latest BIOS 1.27 from Lenovo through Windows. Just wondering whether thers're any differences between installing the BIOS in Windows and Linux. Does fwupd offer exact the same BIOS as the what Lenovo offered but just to be installed in Linux?

**Comment by dal00** [comment]
Ubuntu does not package the latest one which is 20180810.
You should be able to get it from https://www.acpica.org/downloads/ and build it.

**Comment by BkunS** [comment]
@dal00 Updated the iasl to the latest and everything works! Thank you so much!
