### ISSUE TITLE
Any chance of making this tool support the new BIOS?

### ISSUE THREAD

**Issue by CottonEaster** [fiji-flo/x1carbon2018s3#30]
The new X1C6 BIOS - version 1.30, which enables the S3 sleep state - seems to mess up the touchpad (even more than it was messed up before, after sleep). So, I'd like to try going back to your tool (and setting the BIOS to the Windows sleep state). However, upon running your script [EDIT: with the BIOS set to the Windows sleep state], I get this:

```
dsdt.dsl  27617:     Name (\_S3, Package (0x04)  // _S3_: S3 System State
Error    6074 -              ^ Name already exists in scope (\_S3)

    Original name creation/declaration below: 
    dsdt.dsl  27608:         Name (\_S3, Package (0x04)  // _S3_: S3 System State
```

**Comment by fiji-flo** [comment]
That looks like they changed this in a non trivial way. The only way would be to dissect the disassembly from 1.28 and 1.30 and figure out the changes. But I'm not even sure if that would help. The patch in this repo just surfaces the S3 support. If the new BIOS changes S3 in some way (which would mess up your touchpad support) that would still be the same even with an adopted patch.

 Do you use libinput? Other users reported issues when using synaptics.

**Comment by CottonEaster** [comment]
Thanks. 
I use synaptics. I tried  switching to libinput and I still could not get the touchpad working.
