### ISSUE TITLE
x1 yoga 3rd gen

### ISSUE THREAD

**Issue by lsmith77** [fiji-flo/x1carbon2018s3#32]
since the yoga has not yet received the a bios update, it might be good to make this tool work for the yoga

**Comment by nomeata** [comment]
Have you tried? Maybe it does…

**Comment by fiji-flo** [comment]
@lsmith77 you can take a look at https://gist.github.com/fiji-flo/a597465fb630b558995f11946becc620 and https://github.com/fiji-flo/x1carbon2018s3/blob/master/generate_and_apply_patch.sh

It could be fairly straight forward to adapt.

**Comment by lsmith77** [comment]
indeed it does!
