### ISSUE TITLE
Insecure use of /tmp

### ISSUE THREAD

**Issue by jwilk** [fiji-flo/x1carbon2018s3#5]
The script begins with:
```shell
mkdir -p /tmp/x1carbon2018s3
cd /tmp/x1carbon2018s3
```

So it will happily use `/tmp/x1carbon2018s3`, even when this directory exist and is owned by another (possibly malicious) user.
Please use `mktemp -d` for creating temporary directories.

**Comment by fiji-flo** [comment]
Thanks again.
