### ISSUE TITLE
Results of getting this to work on Ubuntu

### ISSUE THREAD

**Issue by mattip** [fiji-flo/x1carbon2018s3#8]
Thanks for this, I now have it working on Ubuntu 18.04. I needed to slightly modify the instructions:

- the `initrd` line should be extended with `/boot/acpi_override` not `/acpi_override`
- verified requires disabling secure boot, otherwise I see in `dmesg` the lines below and the S3 state is not enabled:

```
[    0.000000] ACPI: DSDT ACPI table found in initrd [kernel/firmware/acpi/dsdt.aml][0x2338b]
[    0.000000] Lockdown: ACPI table override is restricted; see man kernel_lockdown.7
[    0.000000] ACPI: kernel is locked down, ignoring table override
  ```

**Comment by fiji-flo** [comment]
What boot manager are you using? On Arch with `systemd-boot` using just `/acpi_override` is fine.

https://wiki.archlinux.org/index.php/DSDT#Using_modified_code

I'm happy to mention this in the readme if you can provide more details.

**Comment by licyeus** [comment]
I'm also on Ubuntu 18.04, but my `grub.cfg` is working with `initrd  /acpi_override /initrd.img-4.15.0-24-generic` (i.e. didn't need to add full path to `/boot/acpi_override`).

The patched `dsdt.dsl` failed to compile for me (at https://github.com/fiji-flo/x1carbon2018s3/blob/master/generate_and_apply_patch.sh#L24), but I manually applied patches from delta-xi.net and was able to follow remaining steps to a working solution. Thanks much, @fiji-flo. :heart:

**Comment by sangster** [comment]
A newbie chiming in here:

When I was setting this up (with GRUB2), it _seemed_ like the order was significant. ie: `initrdefi /initramfs-4.17.5-200.fc28.x86_64.img /acpi_override` did not work, but `initrdefi /acpi_override /initramfs-4.17.5-200.fc28.x86_64.img` does. This may be BS, but making this swap set everything right on my ThinkPad X1 (6th gen).

While, I'm here: a big thanks and three cheers to @fiji-flo for publicising this excellent repository!

**Comment by mattip** [comment]
@fiji-flo I am using grub2, perhaps it is because I do not have a separate boot partition. It might be sufficient to point out that if there is a prefix to the `/initramfs` location (mine is `/boot/initramfs...` then there should also the same prefix to `/acpi_override`.

**Comment by fiji-flo** [comment]
@mattip That seem about right. I'll add this to the doc.
