### ISSUE TITLE
No '/boot/loader' on my system

### ISSUE THREAD

**Issue by CottonEaster** [fiji-flo/x1carbon2018s3#9]
Am I right in thinking that, on an Ubuntu-based distro (I'm on Mint) that does have systemd (EDIT: but perhaps doesn't use 'systemd-boot'), rather than adding a line to conf file in `/boot/loader`, I need to alter `/etc/modules-load.d.modules.conf`?

**Comment by CottonEaster** [comment]
I tried the following. It produced a kernel panic.

Open Grub-Customizer program.
Locate current boot entry.
Find line reading `initrd /boot/initrd.img [etc.]`.
Change the line to `initrd  /acpi_override /boot/initrd.img [etc.]`.

**Comment by fiji-flo** [comment]
There was a PR (#10) from @dal00 that fixed this. This should take care of adjusting your boot loader. Just revert the changes you did to `/etc/modules-load.d.modules.conf` or an other file.

**Comment by CottonEaster** [comment]
Everything seems to work. Thanks to you both.
